generator:
  cache_size: 1000
  max_payload_size: 4096
  templates_dir: testdata/templates
  default_type: sqli

payload_types:
  - type: sqli
    enabled: true
    max_length: 2048
    encode: true
    templates:
      - SQLI-UNION
      - SQLI-ERROR
  
  - type: xss
    enabled: true
    max_length: 1024
    encode: true
    templates:
      - XSS-BASIC
      - XSS-SCRIPT
